import groovy.json.JsonSlurper

plugins {
    id "java"
}

group = 'net.eca.mcreator'
version = new JsonSlurper().parse(file('src/main/resources/plugin.json'))['info']['version']

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
}

dependencies {
    compileOnly files(mcreator_path + '/2024.4.exe')
    compileOnly fileTree(dir: mcreator_path + '/lib', include: ['*.jar'])
}

tasks.jar {
    archiveFileName.set("eca_plugin_${version}_2024.4.zip")
}
